name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: production
  # Disable npm audit warnings in CI to focus on build/test results
  npm_config_audit_level: moderate

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Clean install to avoid npm optional dependencies issues
        # See: https://github.com/npm/cli/issues/4828
        rm -rf node_modules package-lock.json
        npm install --include=dev

    - name: Run linter
      run: npm run lint || echo "Linting completed with warnings/errors"

    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Build artifacts:"
        ls -la dist/
        echo "📊 Bundle size:"
        du -sh dist/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Clean install to avoid npm optional dependencies issues
        rm -rf node_modules package-lock.json
        npm install --include=dev

    - name: Run tests (if available)
      run: npm run test:run --if-present

  security:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Clean install to avoid npm optional dependencies issues
        rm -rf node_modules package-lock.json
        npm install --include=dev

    - name: Run security audit
      run: npm audit --audit-level=high

    - name: Check for outdated dependencies
      run: npm outdated || true
